### ISSUE TITLE
(unsuprisingly)incompatible with baritone(probably wont be fixed)

### ISSUE THREAD

**Issue by USMP-lancer** [Ladysnake/Automatone#4]
## Some information
Operating system: windows 10
Java version: 17 openjdk
Minecraft version: 1.18.2
automatone version: 0.7.0 embedded (requiem)
fabric mods (if used): 
![image](https://user-images.githubusercontent.com/42185819/178130015-72475f4f-9362-45e8-8d85-fbc800cae616.png)

## Exception, error or logs
Please find your `latest.log` or `debug.log` in this folder and attach it to the issue
[crash-log.txt](https://github.com/Ladysnake/Automatone/files/9078361/crash-2022-07-09_22.25.55-client.txt)
[latest.log](https://github.com/Ladysnake/Automatone/files/9078362/latest.log)

## How to reproduce
Add your steps to reproduce the issue/bug experienced here.
simply crashes upon startup, 
## Modified settings
To get the modified settings run `#modified` in game
none
## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.(the fact that you have to put this here is something else)

**Comment by Pyrofab** [comment]
yep lol

**Comment by USMP-lancer** [comment]
gonna have to get an alternative to baritone lmao

**Comment by wisplite** [comment]
I figured out after 2 hours of debugging this was why my game was crashing (requiem has embedded automatone and I also had baritone installed).

Could you at least make it so you can enable the chat commands with embedded automatone or something? I can't create the modpack I'm trying to create without it.

Edit: nvm, didn't realize it was slash commands

Edit 2: The player just sprints in place instead of moving, even with no other mods enabled.
